name: Java CI with Maven

on:
  push:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  maven_build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [11, 8]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Invoke Jenkins Job for Deployment
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_URL }}  # Set your Jenkins URL in GitHub Secrets
          user: ${{ secrets.JENKINS_USER }}  # Set your Jenkins username in GitHub Secrets
          token: ${{ secrets.JENKINS_TOKEN }}  # Set your Jenkins API token in GitHub Secrets
          job: "your-jenkins-job-name"  # Replace with your Jenkins job name
          parameters: |
            PARAM1=value1
            PARAM2=value2
